// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7u-rWgVezhNrx3QmFwDygfVmYH6z2G5w',
    appId: '1:859264778633:web:f9bdafb046af1a9983e158',
    messagingSenderId: '859264778633',
    projectId: 'task-1d09a',
    authDomain: 'task-1d09a.firebaseapp.com',
    storageBucket: 'task-1d09a.appspot.com',
    measurementId: 'G-5QSGEDMM23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvWGQyqgJtjh-tqmiuZaNvNUBbG8oqQ5o',
    appId: '1:859264778633:android:2ce64d298ac2f98183e158',
    messagingSenderId: '859264778633',
    projectId: 'task-1d09a',
    storageBucket: 'task-1d09a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKrDrgMxnzIHtWrUxHWCkkcofWfTl8UMc',
    appId: '1:859264778633:ios:a70ff510c24e880d83e158',
    messagingSenderId: '859264778633',
    projectId: 'task-1d09a',
    storageBucket: 'task-1d09a.appspot.com',
    iosClientId: '859264778633-2iril7iqt1hgfbqm0i6fajotirf41ct0.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKrDrgMxnzIHtWrUxHWCkkcofWfTl8UMc',
    appId: '1:859264778633:ios:4d8e83d30d6c40e283e158',
    messagingSenderId: '859264778633',
    projectId: 'task-1d09a',
    storageBucket: 'task-1d09a.appspot.com',
    iosClientId: '859264778633-bru5pcgpg08fbavjh8588h0de46d72fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.task.RunnerTests',
  );
}
